//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pro01
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movimiento
    {
        public int CodMovimiento { get; set; }
        public int CodTarjeta { get; set; }
        public decimal Cargo { get; set; }
        public decimal Abono { get; set; }
        public System.DateTime Fecha { get; set; }
    
        public virtual Tarjeta Tarjeta { get; set; }
    }
}
