//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplicacion__MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class mvc_Producto
    {
        public int ID { get; set; }
        public string Producto { get; set; }
        public string Descripcion { get; set; }
        public decimal Precio { get; set; }
    }
}
