//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConexionTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCLIENTE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblCLIENTE()
        {
            this.tblFACTURA = new HashSet<tblFACTURA>();
        }
    
        public int ID_CLIENTE { get; set; }
        public string CLIENTE { get; set; }
        public int NIT { get; set; }
        public int TELEFONO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblFACTURA> tblFACTURA { get; set; }
    }
}
