//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConexionTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFACTURA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblFACTURA()
        {
            this.tblDETALLEFACT = new HashSet<tblDETALLEFACT>();
        }
    
        public int ID_FACTURA { get; set; }
        public string SERIE { get; set; }
        public int ID_CLIENTE { get; set; }
        public string DIRCLIENTE { get; set; }
        public string NOMCLIENTE { get; set; }
        public System.DateTime FECHA { get; set; }
        public int ID_BODEGA { get; set; }
        public string ESTADOFAC { get; set; }
    
        public virtual tblBodega tblBodega { get; set; }
        public virtual tblCLIENTE tblCLIENTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDETALLEFACT> tblDETALLEFACT { get; set; }
    }
}
