//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConexionTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblInventario
    {
        public int ID_INVENTARIO { get; set; }
        public int ID_BODEGA { get; set; }
        public int ID_PRODUCTO { get; set; }
        public int EXISTENCIA { get; set; }
        public bool PROD_ESTADO { get; set; }
        public System.DateTime FECHA_IN { get; set; }
    
        public virtual tblBodega tblBodega { get; set; }
        public virtual tblProducto tblProducto { get; set; }
    }
}
