//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConexionTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMovimiento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblMovimiento()
        {
            this.tblDETALLEMOV = new HashSet<tblDETALLEMOV>();
        }
    
        public int ID_MOVIMIENTO { get; set; }
        public int ID_BODEGA { get; set; }
        public System.DateTime FECHA { get; set; }
    
        public virtual tblBodega tblBodega { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDETALLEMOV> tblDETALLEMOV { get; set; }
    }
}
