//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConexionTest
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EleganciaDBEntities : DbContext
    {
        public EleganciaDBEntities()
            : base("name=EleganciaDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tblBodega> tblBodega { get; set; }
        public virtual DbSet<tblCLIENTE> tblCLIENTE { get; set; }
        public virtual DbSet<tblDETALLEFACT> tblDETALLEFACT { get; set; }
        public virtual DbSet<tblDETALLEMOV> tblDETALLEMOV { get; set; }
        public virtual DbSet<tblFACTURA> tblFACTURA { get; set; }
        public virtual DbSet<tblInventario> tblInventario { get; set; }
        public virtual DbSet<tblMovimiento> tblMovimiento { get; set; }
        public virtual DbSet<tblProducto> tblProducto { get; set; }
    }
}
